### ISSUE TITLE
Flag improper use of [Import] on property with no setter

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-mef#103]
When `[Import]` appears on an auto-property with no setter, VS MEF will not be able to set the property at runtime. We should either support this (by some fancy reflection) or define an analyzer that will produce an error in such a case. 
The corrective action would be to explicitly add a `private set;` accessor.

**Comment by weltkante** [comment]
An alternate solution is using `[field: Import]` on auto-properties instead of adding private setters.
