### ISSUE TITLE
TypeRef.Equals should check assembly MVID

### ISSUE THREAD

**Issue by dgriffen** [Microsoft/vs-mef#126]
Currently `TypeRef.Equals` does not check the MVID of its assembly, just the full assembly name. This is inconsistent with the check that `TryUseFastReflection` uses. Meaning that cache equality comparisions can return `true` but slow reflection would still have to be used.

**Comment by dgriffen** [comment]
Looking into this more I don't think TypeRef is actually the correct place for this change. The issue is that TypeRef was meant to be considered equal even if the MVIDs were different. If this was not the case then you wouldn't be able to grab an export from a slightly stale catalog since the two types would not be considered equal. @AArnott, thoughts?

**Comment by AArnott** [comment]
Does it already consider metadata token in equality checks? If so, then we must already have code in place to handle your scenario.
