### ISSUE TITLE
[QUESTION] Example of documentation claim

### ISSUE THREAD

**Issue by jzabroski** [microsoft/vs-mef#134]
Can you please document, inline, in [Why VS-MEF?](https://github.com/microsoft/vs-mef/blob/master/doc/why.md), what you mean by:

> VS MEF utilizes a fully precomputed and validated composition graph for maximum throughput when constructing MEF exports. This also produces a complete list of compositional diagnostics that describe MEF parts that were rejected from the graph with root causes and cascading effects identified.

Seems cool, but hard to wrap my head around the claim.  Even pointing to what test cases assert this functionality would be super helpful.

**Comment by AArnott** [comment]
Great question. I've added the inline link you requested to the doc.

**Comment by jzabroski** [comment]
Thanks, @AArnott  - Have a great memorial day weekend!
