### ISSUE TITLE
Avoid memory leak for IDisposable/NonShared exports

### ISSUE THREAD

**Issue by znakeeye** [microsoft/vs-mef#135]
Consider the sample below. When the exported type implements `IDisposable` the container keeps a reference to _all_ created values, even if they are _non-shared_. This easily causes significant memory leaks.

What is the recommended pattern here?

```c#
using System;
using System.ComponentModel.Composition;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.VisualStudio.Composition;
using CreationPolicy = System.ComponentModel.Composition.CreationPolicy;

namespace MefTest
{
    [Export(typeof(ViewModel)), PartCreationPolicy(CreationPolicy.NonShared)]
    public class ViewModel : IDisposable
    {
        private byte[] bytes;
        public ViewModel() => bytes = new byte[100000]; // Leak
        public void Dispose() {}
    }

    class Program
    {
        static void Main(string[] args)
        {
            var t = InitMef();
            t.Wait();

            var container = t.Result;

            for (var i = 0; i < 100; i++)
            {
                var model = container.GetExportedValue<ViewModel>();
                model.Dispose(); // Container keeps a reference here!
            }

            // NOTE: I want to keep my container.
            // How do I release the memory allocated above?
            // container.Dispose();
        }

        private static async Task<ExportProvider> InitMef()
        {
            var discovery = PartDiscovery.Combine(new AttributedPartDiscoveryV1(Resolver.DefaultInstance));

            var catalog = ComposableCatalog.Create(Resolver.DefaultInstance)
                .AddParts(await discovery.CreatePartsAsync(Assembly.GetExecutingAssembly()))
                .WithCompositionService();

            var config = CompositionConfiguration.Create(catalog);
            var epf = config.CreateExportProviderFactory();
            var exportProvider = epf.CreateExportProvider();

            return exportProvider;
        }
    }
}
```

**Comment by AArnott** [comment]
Thank you for the excellent bug report. I can imagine how we may have missed this in our testing.

**Comment by znakeeye** [comment]
Note that this behavior was probably by design in the original MEF, as stated [here](https://github.com/microsoftarchive/mef/blob/master/Wiki/Parts%20Lifetime.md#container-and-parts-references).
_"We also need to provider a container that has a deterministic behavior"_

Not sure if that decision was right though. In our case, this causes severe memory leaks. As soon as you have classes implementing `IDisposable` you are in trouble.

In `.NET` you have this [ReleaseExport](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.hosting.compositioncontainer.releaseexport?view=netframework-4.8) method. Not sure if it is the right pattern, but at least it gives you the ability to release the memory.

**Comment by AArnott** [comment]
Yes, it's by design that the container maintains references to disposable values. But once a NonShared disposable value has been disposed of by itself, I believe there's no reason for the container to retain its reference. 

I imagine the `ExportLifetimeContext<T>` or `Export<T>` `Dispose()` method should not only dispose the `T` value but remove the reference from the container.

But now that I look at your code a bit more, I see you don't have either of those wrappers, since you're calling `GetExportedValue<T>` so all you get back is a `T`. So in fact this "leak" may in fact be by design. We'll have to review.

In the meantime, can you try using an `ExportFactory<T>` instead to create the instances you need? That will give you the wrapper, and that wrapper may already release the container's reference when you dispose the value.

**Comment by znakeeye** [comment]
I noticed that you have this `IDisposableObservable` interface. When having MEFed disposables, should we use that interface?

**Comment by AArnott** [comment]
You don't need to. Mef doesn't do anything special with that interface.

**Comment by zivkan** [comment]
How is `ExportFactory<T>` used?

Right now, I have a VS extension that does something similar to:
```csharp
var componentModel = AsyncServiceProvider.GlobalProvider.GetServiceAsync<SComponentModel, IComponentModel>();
using (var myThing = componentModel.GetService<MyThing>()) { }
```

this leaks, as per the issue. I tried using `componentModel.GetService<ExportFactory<MyThing>>()`, but it throws with exception message "Expected 1 export(s) with contract name "System.ComponentModel.Composition.ExportFactory(MyThing)" but found 0 after applying applicable constraints."

**Comment by AArnott** [comment]
@zivkan please see #168 for a test that demonstrates no memory leak when using `ExportFactory<T>`. 

Some key points:
1. Define a *shared* MEF part that imports an `ExportFactory<T>` where `T` is your non-shared part.
1. Acquire your shared MEF export and utilize its `ExportFactory<T>` to get an `Export<T>`.
1. Avoid the memory leak by disposing of the `Export<T>` itself when you're done. If `T : IDisposable` then it will be automatically disposed as well.

**Comment by AArnott** [comment]
The workaround is only partially effective when there is a chain of NonShared parts: only the leaf one that you originally acquired ever gets released.

**Comment by AArnott** [comment]
I'm taking a look at this now.
