### ISSUE TITLE
ComposeExportedValue equivalent?

### ISSUE THREAD

**Issue by znakeeye** [microsoft/vs-mef#136]
For `MEF` you have the [ComposeExportedValue](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.attributedmodelservices.composeexportedvalue?view=netframework-4.8) method to export a specific instance.

E.g. in [Prism](https://github.com/PrismLibrary/Prism), this method is used to register pre-created instances when setting up the container. Not sure how to mimic that with `Vs-mef`. Ideas?

**Comment by weltkante** [comment]
[The docs go briefly over this scenario.](https://github.com/microsoft/vs-mef/blob/master/doc/dynamic_recomposition.md) Just have some properties that export the desired services and fill them during startup before dependent services are initialized. I usually make a private nested class for seeding such services together with container initialization. Sometimes you can also just export static properties if your service is process wide.

**Comment by AArnott** [comment]
@weltkante is correct. Thanks for responding.

**Comment by znakeeye** [comment]
Still a bit unclear. Should I export a nested class with properties of e.g. type `ILogger` which I explicitly set to a pre-created instance? Then what?

**Comment by znakeeye** [comment]
Thanks. It's clear now 😛. Even though I will probably never fully understand how the container can be aware of that property being set.

**Comment by AArnott** [comment]
> Even though I will probably never fully understand how the container can be aware of that property being set.

The container is *not* aware of you setting the property. That's why for this to work it's imperative that you set the property *before* any other MEF part might import the value of that property, or else the default value will be snapped into the importing part rather than the value you intended.

**Comment by znakeeye** [comment]
Bah! I get it now 😃
