### ISSUE TITLE
Non-generic ExportProvider.GetExports(Type) method missing

### ISSUE THREAD

**Issue by znakeeye** [microsoft/vs-mef#137]
Given a `Type` variable, how can I get its export?

```c#
public object Resolve<T>() => exportProvider.GetExportedValue<T>();          // OK
public object Resolve(Type type) => exportProvider.GetExportedValue(type);   // ??
```

**Comment by AArnott** [comment]
You can acquire an export without the generic type parameter using `ImportDefinition`, which is ultimately what the generic method uses:

https://github.com/microsoft/vs-mef/blob/83063c3da5504c20595aa263308f6daf584f9b24/src/Microsoft.VisualStudio.Composition/ExportProvider.cs#L795-L820

I'm not sure all the members used above are publicly exposed, but it is possible to do it, perhaps with a bit of code copying.

**Comment by znakeeye** [comment]
> You can acquire an export without the generic type parameter using `ImportDefinition`, which is ultimately what the generic method uses:

Yes, but `ContractNameServices` is _internal_. So it becomes hard to write this method without modifying `vs-mef`.

Do you believe `vs-mef` would benefit from public methods for `Type` variants?

**Comment by AArnott** [comment]
> Yes, but ContractNameServices is internal. So it becomes hard to write this method without modifying vs-mef.

True. That functionality is actually exposed semi-publicly through the `PartDiscovery` class:

https://github.com/microsoft/vs-mef/blob/83063c3da5504c20595aa263308f6daf584f9b24/src/Microsoft.VisualStudio.Composition/PartDiscovery.cs#L183-L186

You could derive from that type, and from there you can call `GetContractName` from a static method you expose publicly. 

> Do you believe vs-mef would benefit from public methods for Type variants?

Perhaps. I think yours is the first case I've heard of that wanted it. We generally want more than one case before adding public API. If you can elaborate on why this is important for you that would help justify work/changes in this area.

**Comment by weltkante** [comment]
> If you can elaborate on why this is important for you

I cannot speak for the OP, but I had the same requirement  a few years ago when I had to implement `IServiceProvider` through a composition container. I don't remember how I solved it back then, but I did get it to work via vs-mef at some point.

I think if you expose GetContractName publically that should be enough, I think you can just pass `object` into the generic parameter of e.g. `GetExportedValue` together with the contract name, something like that already seems to work (unless there is a hidden edge case where it fails?):

```C#
public static class ContainerExtensions
{
    private abstract class PartDiscoveryHelper : PartDiscovery
    {
        private PartDiscoveryHelper(Resolver resolver) : base(resolver) { }
        public static string GetContractNameHelper(Type type) => GetContractName(type);
    }

    public static object GetExportedValue(this ExportProvider container, Type type)
    {
        return container.GetExportedValue<object>(PartDiscoveryHelper.GetContractNameHelper(type));
    }
}
```

**Comment by AArnott** [comment]
Yes, that should work. Thanks for sharing, @weltkante.

(VS-)MEF usually includes the `T` type parameter as an exact match type constraint on the export, but `T=object` is a special case that simply removes the constraint so that any exported value matches. Which is why the contract name becomes so important since that's the only remaining constraint to filter all exports down to (presumably) just one.

**Comment by znakeeye** [comment]
@AArnott, I'm trying to replace `MEF` with `Vs-mef` in a `Prism` application. Before doing so, I decided to benchmark it using [IocPerformance](https://github.com/danielpalme/IocPerformance). In their framework, their APIs use a `Type` variable. Hence my question.

For `Mef` it looks like this (a bit ugly, I'd say):
```c#
public override object Resolve(Type type) =>
    this.container.GetExports(type, null, null).First().Value;
```

And for `Mef2`:
```c#
public override object Resolve(Type type) => this.container.GetExport(type);
```

Personally, I think that any low-level `Foo<T>` API should have a `Foo(Type t)` equivalent. The `Type` variants allow for advanced reflection and/or [lambda expressions](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.lambdaexpression?view=netframework-4.8).

**Comment by znakeeye** [comment]
Also, I don't think that extension method will work in all cases since `typeof(T)` will be `object`:

```c#
contractName = string.IsNullOrEmpty(contractName) ?
     ContractNameServices.GetTypeIdentity(typeof(T)) : contractName;                 // OK!
// ...
var constraints = ImmutableHashSet<IImportSatisfiabilityConstraint>.Empty
     .Union(PartDiscovery.GetExportTypeIdentityConstraints(typeof(T)));              // WRONG? 
// ...
var importMetadata = PartDiscovery.GetImportMetadataForGenericTypeImport(typeof(T)); // WRONG?
```

I'll create a PR.

**Comment by weltkante** [comment]
> Also, I don't think that extension method will work in all cases since typeof(T) will be object

Thats the whole point, I'm passing the contract name, which overrides the typeof(T). As far as I know the various MEF frameworks, once you have a contract name the type becomes irrelevant (except for casting the return value, which will never fail for T=object)

**Comment by weltkante** [comment]
I see what you mean, I guess both could be considered limitations of the extension method though, at least for what I'm doing these kinds of exports never come up.

```C#
var constraints = ImmutableHashSet<IImportSatisfiabilityConstraint>.Empty
     .Union(PartDiscovery.GetExportTypeIdentityConstraints(typeof(T)));              // WRONG? 
```
I don't think this is a serious limitation, when you use the extension method you don't have an explicit contract name, so the contract name comes from the type. It will only cause problems if you intentionally export things under a fake contract name which happens to collide with a type name (something like exporting a string under the ILogger contract, then my extension method will indeed return the string).

```C#
var importMetadata = PartDiscovery.GetImportMetadataForGenericTypeImport(typeof(T)); // WRONG?
```
I think this only affects matching open generic exports, so you can import `ILogger<string>` from an `[Export(ILogger<>)]` normally, but not with the extension method

**Comment by AArnott** [comment]
Interesting. Thanks for sharing those MEFv1 and v2 snippets with me, @znakeeye. I see now that these MEF libraries offer a non-generic GetExports method that VS-MEF is simply missing. In that case, there's precedent for it and filling this hole seems reasonable.

**Comment by AArnott** [comment]
Specifically I think what we should add is an equivalent for [this method](https://apisof.net/catalog/System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(Type,Type,String)):

```cs
public IEnumerable<Lazy<object, object>> GetExports(Type type, Type metadataViewType, string contractName);
```

**Comment by znakeeye** [comment]
> Specifically I think what we should add is an equivalent for [this method](https://apisof.net/catalog/System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(Type,Type,String)):
> 
> ```cs
> public IEnumerable<Lazy<object, object>> GetExports(Type type, Type metadataViewType, string contractName);
> ```

In `Prism` you have a service locator that pretty much relies on this method. See the overridden methos in [MefServiceLocatorAdapter](https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Mef.Wpf/MefServiceLocatorAdapter.cs). Is there a workaround or is this new API strictly needed?

**Comment by AArnott** [comment]
Yes, you could workaround it via Reflection to construct the closed generic method call you need with the Type instance you have.

**Comment by AArnott** [comment]
There are simpler ways to do it, but here is a sample: https://github.com/neuecc/MessagePack-CSharp/blob/3b33ff353049f6a987f2abfad6d1299dd593084e/src/MessagePack/MessagePackSerializer%2BNonGeneric.cs#L83

**Comment by znakeeye** [comment]
I managed to create an extension method for the following method:
```c#
IEnumerable<object> GetExportedValues(Type type, string contractName) 
```

Getting it done for the very much needed `GetExported()` method is way harder due to the complex conversion needed for the return value. 😢

```c#
IEnumerable<Lazy<object, object>> GetExports(Type type, Type metadataViewType, string contractName); 
```

__Source code__

```c#
public static class ExportProviderExtensions
{
    private static readonly Func<Type, CompiledMethods> createCompiledMethods;
    private static readonly ConcurrentDictionary<Type, CompiledMethods> compiledMethods = new ConcurrentDictionary<Type, CompiledMethods>();

    static ExportProviderExtensions()
    {
        createCompiledMethods = t => new CompiledMethods(t);
    }

    public static IEnumerable<object> GetExportedValues(this ExportProvider exportProvider, Type type, string contractName)
    {
        return GetOrAdd(type).GetExports(exportProvider, contractName);
    }

    private static CompiledMethods GetOrAdd(Type type) => compiledMethods.GetOrAdd(type, createCompiledMethods);

    private class CompiledMethods
    {
        public readonly Func<ExportProvider, string, IEnumerable<object>> GetExports;

        public CompiledMethods(Type type)
        {
            var method = GetMethod(type, typeof(string));

            var instance = Expression.Parameter(typeof(ExportProvider));
            var arguments = method.GetParameters().Select(p => Expression.Parameter(p.ParameterType)).ToArray();
            var parameters = Enumerable.Repeat(instance, 1).Concat(arguments);
            
            var body = Expression.Call(instance, method, arguments.ToArray<Expression>());
            var convert = Expression.Convert(body, typeof(IEnumerable<object>));

            var delegateType = typeof(Func<,,>).MakeGenericType(typeof(ExportProvider), typeof(string), typeof(IEnumerable<object>));
            var lambda = Expression.Lambda(delegateType, convert, parameters).Compile();
            
            GetExports = (Func<ExportProvider, string, IEnumerable<object>>) lambda;
        }

        private static MethodInfo GetMethod(Type type, params Type[] parameters)
        {
            return typeof(ExportProvider)
                .GetMethods()
                .Where(m => m.Name == nameof(ExportProvider.GetExportedValues))
                .Where(m => m.GetGenericArguments().Length == 1)
                .Single(m => ParametersMatch(m, parameters))
                .MakeGenericMethod(type);
        }

        private static bool ParametersMatch(MethodInfo method, Type[] parameters)
        {
            var ps = method.GetParameters();
            if (ps.Length != parameters.Length)
            {
                return false;
            }

            for (int i = 0; i < ps.Length; i++)
            {
                if (parameters[i] == null && ps[i].ParameterType.IsGenericParameter)
                {
                    continue;
                }

                if (ps[i].ParameterType != parameters[i])
                {
                    return false;
                }
            }
            return true;
        }
    }
}
```
