### ISSUE TITLE
How to use MEF v3?

### ISSUE THREAD

**Issue by znakeeye** [microsoft/vs-mef#145]
In `ExportProviderTests` I see this comment:

```c#
// MEFv3 is more lazy at activating parts than MEFv1 and MEFv2.
```

That sounds like a very interesting feature. We are currently using `MEFv1`  and plan to switch to v2, but v3 sounds even more promising. How do you migrate to v3?

I suppose we need to change this part:

```c#
var discovery = PartDiscovery.Combine(new AttributedPartDiscoveryV1(resolver));
```

**Comment by AArnott** [comment]
> How do you migrate to v3?

That's a pretty broad question. But here is [our hosting doc](https://github.com/microsoft/vs-mef/blob/master/doc/hosting.md) that should help you. The compatibility from V1 or V2 to V3 is pretty high, so we hope the only changes you have to make is to the code that hosts MEF. Your MEF parts themselves shouldn't require any changes unless you rely on [MEFv1's dynamic recomposition](https://github.com/microsoft/vs-mef/blob/master/doc/dynamic_recomposition.md) feature or a couple of [other differences](https://github.com/microsoft/vs-mef/blob/master/doc/mef_library_differences.md).
