### ISSUE TITLE
[Question] Can't get list of exports from DLLs on disk

### ISSUE THREAD

**Issue by bradws** [microsoft/vs-mef#148]
I'm using the MEF plug-in architecture. I have my `ComposablePart.dll` file in the executable's folder. The code is as per below:
```
using System.ComponentModel.Composition;

namespace ComposablePart
{
    [Export]
    public class ComposablePart : IMyInterface
    {
        public string SayHello()
        {
            return "Hello, this is the message!";
        }
    }
}
```
I'm using the example MefHosting class and code at [https://github.com/microsoft/vs-mef/blob/master/doc/hosting.md](https://github.com/microsoft/vs-mef/blob/master/doc/hosting.md) and I can see my ```ComposablePart.dll``` in the ```config.Parts``` property on this line:
```var config = CompositionConfiguration.Create(catalog);```
but then it gets lost.

I tried to:
```var program = exportProvider.GetExports<IMyInterface>().ToList();```
but there are zero elements.

Can you suggest some code to get all the exports from the Dlls (one export per DLL) to populate the list of ```List<IMyInterface>``` ?

**Comment by AArnott** [comment]
Your problem in this case is that you're `[Export]` exports the type that is decorated, but you're querying for one of its interfaces. If you `[Export]` then you need to `GetExports<ComposablePart>()`.

If you want to `GetExports<IMyInterface>` then you need to `[Export(typeof(IMyInterface))]`.

**Comment by bradws** [comment]
Is there a way of doing the export without specifying the [Export] attribute?

 I thought there was a way for the host program to skim through the Dlls and particular interfaces (or class names) and import them into a list just by the name (with no attribute required). Otherwise, the 'plugin' DLL  seems to need either System.ComponentModel.Composition or vs-mef  as a dependency. This means the creator of a plugin that will implement the common interface has to download/install an extra package. I would rather have them simply implement a POCO object.

Is this possible?

Thanks again.

**Comment by AArnott** [comment]
> Is there a way of doing the export without specifying the [Export] attribute?

Yes. You can build your own `PartDiscovery`-derived class that looks for interface types that you find interesting instead of attributes. You can look at our two derived types for inspiration on how to do this. Our derived classes can look rather complicated because the attributes have so many subtle behaviors, but ultimately you're just responsible for creating a `ComposablePartDefinition` any time you identify a type that exports or imports something and should be included in the catalog.
