### ISSUE TITLE
Host app can't get the plug-in DLLs from a folder other-than the executable's folder!?!

### ISSUE THREAD

**Issue by bradws** [microsoft/vs-mef#149]
I'm trying put my developer-created plugins into a different folder other than the folder where the executable is held. But I keep getting the error:

> "System.IO.FileNotFoundException: 'Could not load file or assembly 'ComposablePart, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified."

 I'm using the example code from [https://github.com/microsoft/vs-mef/blob/master/doc/hosting.md](https://github.com/microsoft/vs-mef/blob/master/doc/hosting.md)

For example: if I drop my DLLs which have a class that implements the 'IMyInterface' interface, then my HOST application can see them, and can execute code from those DLLs. _This is working fine._

However, if I create a 'plugins' folder under the folder where the executable (and its dependencies) resides, and add the line:
`directoryToSearch = Path.Combine(directoryToSearch, "plugins");`
to append the path, I still get that error.

Stepping through, it seems to correctly 'see' the developer-created plugin DLL file on disk, and loads it in, however it fails on the first `yield` clause. (It fails on the first `yield` clause even if I have >= 1 DLL in the folder).

I thought it may have something to do with the DLLs dependencies, so as a test I copied all the output executable files and DLLs into the 'plugins' folder, but the error still occurs.

I have tried different folders, and literal folder strings. I've hard-coded the existing output folder to a literal string - and that worked just fine - it's only when I change the folder to something different to this !?!
 
What am i doing wrong? Surely you can have a different folder for your run-time plugins?

bradws.

**Comment by AArnott** [comment]
MEF doesn't care what folder the assemblies come from. If you provide paths to them it will load and scan them just fine. But when the *CLR* needs to load the assemblies (without a path specified) it won't find them unless those assemblies are in your probing path or you've provided codebase paths for each one. 
If you have a single "plugins" sub-folder, change your App.config file to include plugins in your probing path and I think this will resolve your issue.

**Comment by bradws** [comment]
Thank-you.

I read: [https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies](https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies) and it now works perfectly.

I got confused as there is culture-specific assets involved which means the probing is done differently.
I put the following into my `<configuration>` file thus the CLR was able to probe the _plugins_ folder:

```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <probing privatePath="plugins"/>
        </assemblyBinding>
</runtime>
```

bradws.
