### ISSUE TITLE
Missing symbols for MS.VS.Composition.NetFxAttributes.dll v.15.8.117+g6539dddc3e.RR

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vs-mef#150]
Inserting Live Share 1.0.615 into VS we got a [SymbolCheck failure](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958010/). One of the dlls it complains about is `Microsoft.VisualStudio.Composition.NetFxAttributes.dll`. We ship version 15.8.117+g6539dddc3e.RR

If you publish only portable pdbs, can you also please publish Windows pdbs? Insertion checks for Windows ones.

**Comment by AArnott** [comment]
It looks like that version we had a bug where we archived some pdb's from the build and not this one. I'll see what we can do.

**Comment by AArnott** [comment]
I have a15996de24eab1a7dcf56ba3d3d827762216b660 to fix this. But I wonder where to merge it. Is there some reason Live Share still consumes the 15.8 version? I can fix 15.8 but you'll need to upgrade your package reference.

**Comment by IlyaBiryukov** [comment]
Live Share still supports 15.8. Upgrading the package reference is fine.
