### ISSUE TITLE
Host app can't get the plug-in DLLs from a folder other-than the executable's folder in .NET Core!?!

### ISSUE THREAD

**Issue by bradws** [microsoft/vs-mef#153]
Hello,

I have my [previous issue](https://github.com/microsoft/vs-mef/issues/149) resolved for .NET Framework, but I'm having problems porting the app over to .NET Core.

It works in .NET Framework just fine, but i just can't seem to get it working in .NET Core.

After much research, it looks like .NET Core doesn't have the equivalent feature:
```
    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <probing privatePath="Plugins"/>
        </assemblyBinding>
    </runtime>

```
...like it has in .NET Framework.

It appears (at this point) there is no real way for your host app to tell the .NET Core CLR where to resolve the dependencies when you have globalisaiton (i.e. vs-mef) and you want to specify a folder where your plug-in DLLs reside.

References
[https://stackoverflow.com/questions/46764925/exporting-interface-from-class-net-core](https://stackoverflow.com/questions/46764925/exporting-interface-from-class-net-core)

[https://github.com/dotnet/cli/issues/11713](https://github.com/dotnet/cli/issues/11713)

[https://stackoverflow.com/questions/56844233/additional-probing-paths-for-net-core-3-migration](https://stackoverflow.com/questions/56844233/additional-probing-paths-for-net-core-3-migration)

Is there anyway or suggestions this can work in .NET core 3 ?

**Comment by AArnott** [comment]
This doesn't sound like a VS-MEF specific issue. Rather, it sounds like your issue is "how to load assemblies from other locations on .NET Core?" Once you have that answered, VS-MEF should Just Work. 

Here's a tip (I haven't tried it): https://natemcmaster.com/blog/2018/07/25/netcore-plugins/
