### ISSUE TITLE
How to force single export of Test class?

### ISSUE THREAD

**Issue by znakeeye** [microsoft/vs-mef#154]
My container graph is built in `Main.dll` where `MainFoo` is exported:

```c#
[Export(typeof(IFoo)), PartCreationPolicy(CreationPolicy.Shared)]
public MainFoo : IFoo { }
```

Now, in my unit test I want to use a testable `IFoo` implementation, using the technique described [here](https://github.com/microsoft/vs-mef/blob/master/doc/dynamic_recomposition.md#adding-parts-directly-with-compositioncontainercompose).

```c#
var testServices = Container.GetExportedValue<TestServices>();
testServices.Foo = new TestFoo();

[Export]
protected sealed class TestServices
{
    [Export] public IFoo Foo { get; set; }
}
```

Later, when querying the value...

```c#
var foo = Container.GetExportedValue<IFoo>();
```

**The problem**
I get a somewhat expected composition exception. How can I prevent `MainFoo` from being added in the graph? Please note that I must include `Main.dll` in my graph.

```
Message: 
  Test method ... threw exception: 
  Microsoft.VisualStudio.Composition.CompositionFailedException:
    Expected 1 export(s) with contract name "Main.IFoo"
    but found 2 after applying applicable constraints.
Stack Trace: 
  at ExportProvider.GetExports(ImportDefinition importDefinition)
  at ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
  at ExportProvider.GetExport[T,TMetadataView](String contractName)
  at ExportProvider.GetExport[T](String contractName)
  at ExportProvider.GetExport[T]()
  at ExportProvider.GetExportedValue[T]()
  at Tests.TestFoo()
```

I guess I need to introduce some kind of precedence rule. I.e. when the Test.dll assembly is available its Main-equivalent exports should be used instead. Is this even possible?

**Comment by znakeeye** [comment]
Should I perhaps wrap my container in a `FilteringExportProvider` as shown in [DelegatingExportProviderTests.cs](https://github.com/microsoft/vs-mef/blob/master/src/tests/Microsoft.VisualStudio.Composition.Tests/DelegatingExportProviderTests.cs)?

**Comment by AArnott** [comment]
> Should I perhaps wrap my container in a FilteringExportProvider as shown in DelegatingExportProviderTests.cs?

No, a FilteringExportProvider would not impact the graph -- only the exports you get when imperatively querying for them. So if anyone had `[Import] IFoo` that part would be rejected in the tests because two `IFoo` exports exist in the catalog.

Regarding your `TestServices` class, you don't need to export it (unless you're literally importing it somewhere). You only need the export on the exporting members.

You have to prevent the Main.dll's `MainFoo` from entering your catalog, since you can't simply remove it from the catalog due to #73.
You can do this by performing assembly-level discovery on Main.dll, and then before putting the discovered parts into a catalog, filter out your MainFoo from the collection of parts.

**Comment by znakeeye** [comment]
Thanks. Perhaps `vs-mef` could provide a callback interface on the catalog level. Something like `IPartCallback.IncludePart` as shown below?

```c#
// IPartCallback implementation
public bool IncludePart(ComposablePartDefinition partDefinition)
{
     return true; // Filtering logic here...
}

public void BuildContainer()
{
     var catalog = ComposableCatalog.Create(resolver, this); // 2nd argument is IPartCallback!
     // Add parts...
}
```

**Comment by AArnott** [comment]
Would that be easier for you than just implementing #73?

**Comment by znakeeye** [comment]
Implementing #73 is a better idea.

**Comment by znakeeye** [comment]
> Regarding your `TestServices` class, you don't need to export it (unless you're literally importing it somewhere). You only need the export on the exporting members.
> 

If I don't export it I cannot get the exported value as shown below:

```c#
var testServices = Container.GetExportedValue<TestServices>();
```

What would be the right way then?

**Comment by AArnott** [comment]
You are correct. 
But from the little snippets you've shared, it seemed that `TestServices` wasn't there to be exported for its own value, but rather for all the property getters that it contained.

So for example this class, where I've removed the extra export attribute:

```cs
protected sealed class TestServices
{
    [Export] public IFoo Foo { get; set; }
}
```

This will work fine in exporting an `IFoo` for your tests to import or call `GetExportedValue<IFoo>` on. Why would anyone ever need to import `TestServices` itself? What else does it have to offer?

**Comment by znakeeye** [comment]
I guess `TestServices` would just be a placeholder for the exported values (there are a few).

Also, it's worth mentioning that it's probably a good idea to use `CreatePartsAsync` that takes a list of `Type`. That way you can export only the `TestServices` members, and not all `ExportAttribute` attributed classes in the assembly (which is a relevant scenario for unit testing).

Correct me if I'm wrong.

**Comment by AArnott** [comment]
Yes, I generally do not add the entire test assembly to the catalog for just that reason: focused testing with specific exports I define for a test.
You can pass `TestServices` itself to the part discoverer class and all its exports will be discovered.

**Comment by znakeeye** [comment]
> Yes, I generally do not add the entire test assembly to the catalog for just that reason: focused testing with specific exports I define for a test.
>

Thanks. Please add this piece of information to the documentation! (It took me quite some time to figure this out.)
