### ISSUE TITLE
Clarify comment for Resolver.DefaultInstance

### ISSUE THREAD

**Issue by rhettc** [microsoft/vs-mef#162]
The summary for the field `Resolver.DefaultInstance` mentions that this should only be used for debugging purposes. Is there documentation that clarifies how someone that is using VS MEF in a new project should provide an appropriate version of `IAssemblyResolver`?  The caveats for using the DefaultInstance are not clear. Thanks!

**Comment by AArnott** [comment]
Great feedback. That was probably written at a time where we weren't sure where we'd land. The comment is bad.
