### ISSUE TITLE
Where are the release notes?

### ISSUE THREAD

**Issue by znakeeye** [microsoft/vs-mef#170]
Where can you see what was fixed in e.g. [v16.4.11](https://github.com/microsoft/vs-mef/releases/tag/v16.4.11)?

**Comment by AArnott** [comment]
I'm afraid we haven't done a great job of publishing release notes in this repo. I published [the release notes for 16.4.11](https://github.com/microsoft/vs-mef/releases/tag/v16.4.11) for you..
