### ISSUE TITLE
Support for [TypeForwardedTo]

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/vs-mef#18]
From my observations VSMEF doesn't seem to unify types which are type forwarded?

For instance, you have `SourceAssembly1` with `Interface1`. `ProjectA` references `SourceAssembly1` and has `[assembly:TypeForwardedTo(typeof(Interface1))]`. `ProjectB` references `ProjectA` and defines `TypeB : Interface1`.

At runtime if I have an `[Import] Interface1 I1` it doesn't seem to get satisfied with:
```
I1: is not assignable from exported MEF value TypeB.
```

Not saying this is a bug, but just wanted to clarify the design: is this even supposed to work? Should type forwarders be followed and unified?

**Comment by AArnott** [comment]
If the CLR sees them as the same at runtime, I think we should too during the discovery phase.
We support NoPIA, after all.

**Comment by AArnott** [comment]
@KirillOsenkov Would you be able to submit a PR that adds the failing test for this?

**Comment by KirillOsenkov** [comment]
How do I say `no` very politely :)

**Comment by AArnott** [comment]
Here's one way:
![No](https://media.giphy.com/media/eX4TDuw5z4PrW/giphy.gif)

**Comment by AArnott** [comment]
I would expect this to work. MEF doesn't try to guess whether one type is assignable to another, but rather relies on the CLR to do it. So type forwarding should work. Without a repro or a strong ask, I'm going to close this.
