### ISSUE TITLE
Composition Analyzer package does not install when using packages.config

### ISSUE THREAD

**Issue by JoeRobich** [microsoft/vs-mef#198]
This analyzer package is missing the install.ps1 and uninstall.ps1 scripts that allow it to work in packages.config projects. It will only work for `<PackageReference>`.

The following error is logged in VS's NuGet Package Manager:

> Could not install package 'Microsoft.VisualStudio.Composition.Analyzers 16.9.6-alpha'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

For more information on this, see [Analyzer Conventions - Install and Uninstall scripts](https://docs.microsoft.com/en-us/nuget/guides/analyzers-conventions#install-and-uninstall-scripts).

**Comment by JoeRobich** [comment]
@AArnott Will a new build of this package be published to NuGet for 16.9 GA? This issue is blocking Roslyn's Microsoft.VisualStudio.LanguageServices package from installing when using a packages.config.

**Comment by AArnott** [comment]
v16.9.20 is on its way to nuget.org now.
