### ISSUE TITLE
Install of latest alpha 16.9.6 fails for .NET-Framework 4.7.2

### ISSUE THREAD

**Issue by Maximilian-Renner** [microsoft/vs-mef#200]
Hi there,

the current alpha version seems not to be compatible with .NET-Framework V4.7.2 .
NuGet page (`https://www.nuget.org/packages/Microsoft.VisualStudio.Composition/16.9.6-alpha`) states, that it can be used with .NET-Framework. But if I try to install the nuget package on my project, it will fail as the dependency Microsoft.VisualStudio.Composition.Analyzers doesn't seems to be compatible

Here is the NuGet log:

@ Installing Microsoft.VisualStudio.Composition in MyDummyProject started
Attempting to gather dependency information for package 'Microsoft.VisualStudio.Composition.16.9.6-alpha' with respect to project 'C:\Users\<username>\source\repos\MyDummyProject\MyDummyProject', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 1,28 sec
Attempting to resolve dependencies for package 'Microsoft.VisualStudio.Composition.16.9.6-alpha' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.VisualStudio.Composition.16.9.6-alpha'
Resolved actions to install package 'Microsoft.VisualStudio.Composition.16.9.6-alpha'
Retrieving package 'Microsoft.VisualStudio.Composition 16.9.6-alpha' from 'nuget.org'.
Retrieving package 'Microsoft.VisualStudio.Composition.Analyzers 16.9.6-alpha' from 'nuget.org'.
Retrieving package 'Microsoft.VisualStudio.Composition.NetFxAttributes 16.9.6-alpha' from 'nuget.org'.
Retrieving package 'Microsoft.VisualStudio.Validation 15.5.31' from 'nuget.org'.
Retrieving package 'System.Collections.Immutable 1.5.0' from 'nuget.org'.
Retrieving package 'System.ComponentModel.Composition 4.5.0' from 'nuget.org'.
Retrieving package 'System.Composition 1.0.31' from 'nuget.org'.
Retrieving package 'System.Composition.AttributedModel 1.0.31' from 'nuget.org'.
Retrieving package 'System.Composition.Convention 1.0.31' from 'nuget.org'.
Retrieving package 'System.Composition.Hosting 1.0.31' from 'nuget.org'.
Retrieving package 'System.Composition.Runtime 1.0.31' from 'nuget.org'.
Retrieving package 'System.Composition.TypedParts 1.0.31' from 'nuget.org'.
Retrieving package 'System.Reflection 4.3.0' from 'nuget.org'.
Retrieving package 'System.Reflection.Emit 4.3.0' from 'nuget.org'.
Retrieving package 'System.Reflection.Metadata 1.6.0' from 'nuget.org'.
Retrieving package 'System.Reflection.TypeExtensions 4.3.0' from 'nuget.org'.
Retrieving package 'System.Threading.Tasks.Dataflow 4.11.1' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/system.reflection/4.3.0/system.reflection.4.3.0.nupkg
Install failed. Rolling back...
Package 'Microsoft.VisualStudio.Composition.Analyzers.16.9.6-alpha' does not exist in project 'MyDummyProject'
Package 'Microsoft.VisualStudio.Composition.Analyzers.16.9.6-alpha' does not exist in folder 'C:\<username>\source\repos\MyDummyProject\packages'
Executing nuget actions took 76 ms
Could not install package 'Microsoft.VisualStudio.Composition.Analyzers 16.9.6-alpha'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
System.InvalidOperationException: Could not install package 'Microsoft.VisualStudio.Composition.Analyzers 16.9.6-alpha'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
   bei NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__36.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.PackageManagement.NuGetPackageManager.<ExecuteInstallAsync>d__87.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__77.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__77.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__77.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation.<>c__DisplayClass6_0.<<InstallAsync>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation.<InstallInternal>d__10.MoveNext()

@ Installing Microsoft.VisualStudio.Composition in MyDummyProject finished (1,407 sec)
[Notification][Install] Install failed (project: MyDummyProject, package: Microsoft.VisualStudio.Composition v16.9.6-alpha)
Could not install package 'Microsoft.VisualStudio.Composition.Analyzers 16.9.6-alpha'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by AArnott** [comment]
Thanks for reporting. This works on an SDK style project that targets net472, but I can repro the problem when starting with the old style project.
