### ISSUE TITLE
Lots of (most likely duplicate) assemblyname instances

### ISSUE THREAD

**Issue by Therzok** [microsoft/vs-mef#251]
It seems like for each assemblyname queried, there is a normalized assemblyname being created. Maybe it's worth having a normalized map to reduce the number of assemblyname instances?

![image](https://user-images.githubusercontent.com/109974/131215719-7788aa37-d214-4400-9745-316a6c7f7a3a.png)

**Comment by Therzok** [comment]
The problem seems to be worse, since each AssemblyName contains a CultureInfo and a NumberFormatInfo, so a total of 7MB (60000 objects) is retained when it could be deduplicated.

**Comment by Therzok** [comment]
They seem to come from these calls [1](https://github.com/microsoft/vs-mef/blob/0fbe01af5cf29c2733320a169c1027fe3f568fa9/src/Microsoft.VisualStudio.Composition/Reflection/TypeRef.cs#L68) [2](https://github.com/microsoft/vs-mef/blob/0fbe01af5cf29c2733320a169c1027fe3f568fa9/src/Microsoft.VisualStudio.Composition/Reflection/TypeRef.cs#L90) where [copies are created](https://github.com/microsoft/vs-mef/blob/0fbe01af5cf29c2733320a169c1027fe3f568fa9/src/Microsoft.VisualStudio.Composition/Reflection/TypeRef.cs#L437)

Based on the fact that the more common constructor is [this one](https://github.com/microsoft/vs-mef/blob/0fbe01af5cf29c2733320a169c1027fe3f568fa9/src/Microsoft.VisualStudio.Composition/Reflection/TypeRef.cs#L83) and that `Assembly.GetName()` always creates a copy of the assemblyname, I think that maybe a `ConditionalWeakTable<Assembly, AssemblyName>` or `Dictionary<Assembly, AssemblyName>` could be used.

**Comment by Therzok** [comment]
Draft PR for fixing this: https://github.com/microsoft/vs-mef/pull/252/files#

**Comment by AArnott** [comment]
Great find. Thank you. I think a standard dictionary is appropriate here because no MEF assembly would be expected to be unloaded after inclusion in a graph.
