### ISSUE TITLE
Equivalent SatisfyImportsOnce

### ISSUE THREAD

**Issue by gabrielrvd** [microsoft/vs-mef#392]
Hi, I looking for a method like SatisfyImportsOnce in MEF1. I have a object instanced and need resolve his imports but not find a way to do this. Tks

```
[System.ComponentModel.Composition.Export(typeof(A))]
public class A
{
}

public class B
{
    [Import]
    public A A { get; set; }

    public B()
    {
        // TODO: Here import A using CompositionContainer.SatisfyImportsOnce(this)
        this.A = // Resolve imports
    }
}
```

**Comment by AArnott** [comment]
VS-MEF supports this. MEFv1 defines `SatisfyImportsOnce` as an extension method on `ICompositionService`, which VS-MEF makes available.

Import `ICompositionService` (or call `GetExportedValue<ICompositionService>()`) and call SatisfyImportsOnce on it.

**Comment by gabrielrvd** [comment]
Thank you for your answer. Help me a lot to understand how its works.

For someone with same problem. I was filtering only assemblies that I use, but to use the ICompositionService is necesssary CreatePartsAsync load Microsoft.VisualStudio.Composition.dll of course :).

Another way is create your own CompositionContainer to Mef1, like ICompositionService do.
```
var compositionContainer = new CompositionContainer(CompositionOptions.IsThreadSafe, exportProvider.AsExportProvider());
compositionContainer.SatisfyImportsOnce(this);

```

**Comment by AArnott** [comment]
Yes, I suppose that works too, although now you have another container with its lifetime policies to worry about.
