### ISSUE TITLE
StandardAssemblyLoader.LoadAssembly does not respect codeBasePath on .NET Core

### ISSUE THREAD

**Issue by jaredpar** [microsoft/vs-mef#439]
The implementation of `StandardAssemblyLoader.LoadAssembly` is supposed to consider the `codeBasePath` parameter when locating the assembly. It attempts to do this by setting the `AssemblyName.CodeBase` property before calling `Assembly.Load(AssemblyName)`. 

```csharp
var assemblyName = new AssemblyName(assemblyFullName);
if (!string.IsNullOrEmpty(codeBasePath))
{
    assemblyName.CodeBase = codeBasePath;
}

// ends up calling Assembly.Load(AssemblyName)
return this.LoadAssembly(assemblyName);
```

.NET Core does not respect `AssemblyName.CodeBase` though hence this has no impact there. 

The rough equivalent of this pattern for .NET Core is the following: 

```csharp
var alc = 
  AssemblyLoadContext.CurrentContextualReflectionContext 
  ?? AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly());
try 
{
  return alc.LoadFromAssemblyName(new AssemblyName(assemblyFullName);
} 
catch 
{
  return alc.LoadFromAssemblyPath(codeBase);
}
```

Hard to 100% tell what the use case is here though as I can't find callers of `IAssemblyLoader.LoadAssembly(string, string)` in the repo. 

Note: this code will appropriately get SYSLIB0044 warnings when targeting `net8.0`.

**Comment by AArnott** [comment]
You're right about that. And while I knew at the time that it wouldn't work on Core CLR, I didn't know how to 'fix' it. I appreciate your recommendation there.
As I can't find any use of this method within VS-MEF either. And as this interface is intended for consumption by VS-MEF alone, I don't expect anyone outside this repo should be calling it either. So I'm tempted to at least annotate `[Obsolete]` on the method and change the documentation to encourage implementations to simply throw.

I'm curious how you came across this. Do you need it to work? That may dissuade me from the idea of obsoleting the method.

**Comment by jaredpar** [comment]
> I'm curious how you came across this. 

Now that the VS private runtime targets `net8.0` I was moving the TFMs in roslyn [to net8.0](https://github.com/dotnet/roslyn/pull/71507). One of our implementations of `IAssemblyLoader` had this exact pattern in it and triggered SYSLIB0044. 

Before fixing it I wanted to know more how `LoadAssembly(string, string)` was intended to work cause it may change the `AssemblyLoadContext` the load should occur into. This repo defined the interface so I started searching around here and found that the implementations had roughly the same pattern :smile: 

> Do you need it to work? That may dissuade me from the idea of obsoleting the method.

Only if VS-MEF needs it to work. Part of the problem is I couldn't find any callers. If there are no realistic callers then `[Obsolete]` seems good to me
